<?php
$_brandCollection = $block->getCollection();
$show_brand_name = $this->getConfig('brand_list_page/show_brand_name');
?>
<?php /*if ( $_brandCollection->count() ){ ?>
<div class="brands-sidebar-container">
	<ul class="brands-sidebar">
	<?php foreach ($_brandCollection as $_brand) { ?>
		    <li>
		    	<figure>
			    	<a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>">
			               <img class="img-fluid"  alt="<?php echo $_brand->getName(); ?>" src="<?php echo $_brand->getThumbnailUrl(); ?>"/>
			        </a>
		    	</figure>
		   </li>
	<?php } ?>
	</ul>
</div>
<?php } */?>

