<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<form class="form password-forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
        <div class="field email required">
            <label class="label" for="email">
                <a class="sms-login-field-ctrl selected" href="#<?php echo \Vnecoms\Sms\Helper\Data::LOGIN_TYPE_EMAIL;?>"><span><?= $block->escapeHtml(__('Email')) ?></span></a>
                <?php echo __('or')?>
                <a class="sms-login-field-ctrl"  href="#<?php echo \Vnecoms\Sms\Helper\Data::LOGIN_TYPE_MOBILE;?>"><span><?= $block->escapeHtml(__('Mobile')) ?></span></a>
            </label>
            <div id="by_mobile" class="control sms-login-field" style="display: none;">
                <input name="login[mobile]" value="<?= $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="mobile-number-input" type="text"
                       class="input-text mobile-number required-entry validate-sms-phone-number<?php if($block->isEnabledVerifying()):?> otp-verify<?php endif;?><?php if($block->getIsVerifiedMobile()):?> otp-validated<?php endif;?>" title="<?= $block->escapeHtml(__('Mobile')) ?>">
                <input type="hidden" name="mobile_number" id="mobile-number" />
                <input type="hidden" name="login_type" id="login_type" value="<?php echo \Vnecoms\Sms\Helper\Data::LOGIN_TYPE_EMAIL;?>"/>
                <input type="hidden" name="mobile_otp" id="mobile-otp" />
            </div>
            <div id="by_email" class="control sms-login-field">
                <input name="email" value="<?= $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email_address" type="email" class="input-text" title="<?= $block->escapeHtml(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>

<div class="sms-otp-dialog" id="sms-otp-dialog">
    <div class="sms-otp-step-1">
        <p><?php echo __("Click to the button below to verify your phone number")?> <span class="sms-otp-mobile"></span></p>
        <button class="action primary send-otp-btn" id="send-otp-btn"><span><?php echo __("Get OTP")?></span></button>
    </div>
    <div class="sms-otp-step-2">
        <p><?php echo __("A text message with a %1-digit verification code has been sent to your phone number!",$block->getOtpLength())?> <span id="sms-otp-dialog-mobile" class="sms-otp-mobile"></span></p>
        <input type="text" name="sms_otp_code" id="sms-otp-input" value="" class="input-text required-entry" placeholder="<?php echo __("Your OTP")?>"/>
        <button class="action primary send-otp-btn" id="verify-otp-btn"><span><?php echo __("Verify")?></span></button>
        <a href="#" class="resend-otp-btn" id="resend-otp-btn" data-time="<?php echo $block->getOtpResendPeriodTime()?>"><?php echo __("Resend after %1 seconds", $block->getOtpResendPeriodTime())?></a>
    </div>
</div>


<?php
/** @var \Vnecoms\Sms\Helper\Data $smsHelper*/
$smsHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Vnecoms\Sms\Helper\Data');
?>
<script type="text/javascript">
    var URL_SEND_OTP = '<?php echo $block->getSendOtpUrl();?>';
    var URL_VERIFY_OTP = '<?php echo $block->getVerifyOtpUrl();?>';

    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'Magento_Ui/js/modal/alert',
        'jquery/intltellinput',
        'Vnecoms_Sms/js/utils',
        'mage/mage',
        'mage/validation',
        'smsLogin',
        'loader',
        'domReady!'
    ], function($, modal, alert){
        function initMobileInput(){
            $('.password-forget').smsLogin({
                initialCountry: '<?php echo strtolower($smsHelper->getInitialCountry());?>',
                allowDropdown: <?php echo strtolower($smsHelper->getAllowCountryDropdown());?>,
                onlyCountries: <?php echo $smsHelper->isAllowedAllCountries()?'[]':json_encode(explode(",",$smsHelper->getAllowedCountries()));?>,
                preferredCountries:<?php echo json_encode(explode(',', $smsHelper->getPreferredCountries()));?>,
                geoIpUrl: '<?php echo $smsHelper->getGeoIpDatabase()?$this->getUrl('vsms/geoip'):'https://ipinfo.io';?>'
            });
        }

        function showOtpDialog(){
			$('#sms-otp-input').attr('autocomplete', 'one-time-code');
            $('.sms-otp-step-1').show();
            $('.sms-otp-step-2').hide();
            $('#sms-otp-dialog').modal('openModal');
        }


        /**
         * Send otp
         */
        function sendOtp(isResend){
            $.ajax({
                url: URL_SEND_OTP,
                method: "POST",
                data: {
                    mobile : $("#mobile-number").val(),
                    resend : isResend,
                },
                dataType: "json"
            }).done(function( response ){
                if(response.success){
                    $('.sms-otp-step-1').hide();
                    $('.sms-otp-step-2').show();
                    $('#mobile-number-id').val(response.mobile_id);
                    runCountDown();
                }else{
                    alert({
                        modalClass: 'confirm ves-error',
                        title: "<?php echo __("Verify Error");?>",
                        content: response.msg,
                    });
                }

            });
        }

        function runCountDown(){
            var resendBtn = $('#resend-otp-btn');
            if(!resendBtn.hasClass('running')){
                resendBtn.addClass('running');
            }

            if(!resendBtn.data('couting')){
                !resendBtn.data('couting', resendBtn.data('time'));
            }
            var count = parseInt(resendBtn.data('couting'));
            count --;
            resendBtn.data('couting', count);
            resendBtn.html('<?php echo __("Resend after %1 seconds")?>'.replace('%1', count));

            if(count == 0) {
                resendBtn.removeClass('running');
                resendBtn.html('<?php echo __("Resend OTP")?>');
                return;
            }
            setTimeout(function(){runCountDown()}, 1000);
        }



        $('#send-otp-btn').click(function(){
            sendOtp(0);
        });

        $('#resend-otp-btn').click(function(){
            if($('#resend-otp-btn').hasClass('running')){
                return false;
            }
            sendOtp(1);
            return false;
        });

        $('#verify-otp-btn').click(function(){
            $('#sms-otp-error').remove();
            if($(this).hasClass('verifying')){
                return;
            }
            var otp = $('#sms-otp-input').val();
            if(!otp){
                $('#sms-otp-input').after('<div id="sms-otp-error" class="sms-otp-error" for="sms-otp-input"><?php echo __("This is required field.");?></div>');
                return;
            }

            $(this).addClass('verifying');

            $.ajax({
                url: URL_VERIFY_OTP,
                method: "POST",
                data: {
                    mobile : $("#mobile-number").val(),
                    otp: otp
                },
                dataType: "json"
            }).done(function( response ){
                $('#verify-otp-btn').removeClass('verifying');
                $('#sms-otp-input').val('');
                if(response.success){
                    $("#mobile-otp").val(response.otp);
                    $('#mobile-number-input').addClass('otp-validated').validation().validation('isValid');
                    $('#sms-otp-dialog').modal('closeModal');
                    window.location.replace(response.url);
                }else{
                    $('#sms-otp-input').after('<div id="sms-otp-error" class="sms-otp-error" for="sms-otp-input">'+response.msg+'</div>');
                }

            });
        });

        $('#form-validate').submit(function( event ) {
            if($('#login_type').val() != 'by_mobile') return;
            if(!$('#mobile-number-input').intlTelInput("isValidNumber")) {
                alert({
                    modalClass: 'confirm ves-error',
                    title: "<?php echo __("Error");?>",
                    content: "<?php echo __('Please enter a valid mobile number!')?>",
                });
                return;
            }
            showOtpDialog();
            event.preventDefault();
        });

        initMobileInput();

        var options = {
            type: 'popup',
            modalClass:'otp-verify-modal',
            responsive: true,
            innerScroll: true,
            title: '<?php echo __("Verify Your Mobile Number")?>',
            buttons: []
        };
        var popup = modal(options, $('#sms-otp-dialog'));
    });
</script>





