<script>
require([
    "jquery"
    ], function($){
    $('#history_notify').parent().after(
	    '<div class="admin__field admin__field-option">'
	    + '<input name="history[is_sms_notified]" type="checkbox" id="vnecoms_sms_notify" class="admin__control-checkbox" value="1">'
        + '<label class="admin__field-label" for="vnecoms_sms_notify"><?php echo __('Notify Customer by SMS');?></label>'
        + '</div>'
    );
});
</script>