<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Vnecoms\Sms\Block\Customer\Address\Edit $block */

?>
<div class="sms-otp-dialog" id="sms-otp-dialog">
    <div class="sms-otp-step-1">
        <p><?php echo __("Click to the button below to verify your phone number")?> <span class="sms-otp-mobile"></span></p>
        <button class="action primary send-otp-btn" id="send-otp-btn"><span><?php echo __("Get OTP")?></span></button>
    </div>
    <div class="sms-otp-step-2">
        <p><?php echo __("A text message with a %1-digit verification code has been sent to",$block->getOtpLength())?> <span id="sms-otp-dialog-mobile" class="sms-otp-mobile"></span></p>
        <input type="text" name="sms_otp_code" id="sms-otp-input" value="" class="input-text required-entry" placeholder="<?php echo __("Your OTP")?>"/>
        <button class="action primary send-otp-btn" id="verify-otp-btn"><span><?php echo __("Verify")?></span></button>
        <a href="#" class="resend-otp-btn" id="resend-otp-btn" data-time="<?php echo $block->getOtpResendPeriodTime()?>"><?php echo __("Resend after %1 seconds", $block->getOtpResendPeriodTime())?></a>
    </div>
</div>

<script type="text/javascript">
var URL_SEND_OTP = '<?php echo $block->getSendOtpUrl();?>';
var URL_VERIFY_OTP = '<?php echo $block->getVerifyOtpUrl();?>';

document.getElementById('telephone').type = 'hidden';
require([
     'jquery',
     'Magento_Ui/js/modal/modal',
     'Magento_Ui/js/modal/alert',
     'Vnecoms_Sms/js/utils',
     'jquery/intltellinput',
     'jquery/mask',
     'mage/mage',
     'mage/validation'
], function($, modal, alert){
	$('#telephone').after(
	   '<input type="tel" name="mobile_number_input" id="mobile-number-input" value="<?php echo $block->getInitMobileNumber();?>" class="input-text mobile-number required-entry validate-sms-phone-number<?php if($block->isEnabledVerifying()):?> otp-verify<?php endif;?><?php if($block->getIsVerifiedMobile()):?> otp-validated<?php endif;?>" />'+
	   '<input type="hidden" name="mobile_otp" id="mobile-otp" />'
	);
	$('#telephone').parent().parent().addClass('vsms-field-container');
    if($('#telephone').val()){
        $('#mobile-number-input').val($('#telephone').val());
    }

	function initMobileInput(){
	    $("#mobile-number-input").intlTelInput({
	    	initialCountry: '<?php echo strtolower($block->getInitialCountry());?>',
            allowDropdown: <?php echo strtolower($block->getAllowCountryDropdown());?>,
	    <?php if($block->getInitialCountry() == 'auto'):?>
        	geoIpLookup: function(callback) {
        	    $.get("<?php echo $block->getGeoIpUrl();?>", function() {}, "jsonp").always(function(resp) {
     	    	   var countryCode = (resp && resp.country) ? resp.country : "";
     	    	   callback(countryCode);
    		    });
      		},
  		<?php endif;?>
  		onlyCountries: <?php echo $block->getOnlyCountries();?>,
		preferredCountries:<?php echo $block->getPreferredCountries();?>
        }).done(function() {
        	initMask();
           $('#telephone').val($("#mobile-number-input").intlTelInput("getNumber"));
     	   $('#mobile-number-input').on('keyup', function() {
      		   validatePhoneNum();
       	   }).on("countrychange", function(e, countryData) {
          		validatePhoneNum();
          		initMask();
      	   });
      	});
	}

	/**
     * Validate phone number
     */
    function validatePhoneNum(){
        var number = $("#mobile-number-input").intlTelInput("getNumber");
        var currentCustomerNumber = '<?php echo $this->getCustomer()->getMobilenumber()?>';
        if(currentCustomerNumber.length && (number == currentCustomerNumber)){
        	$('#mobile-number-input').addClass('otp-validated');
        }else{
        	$('#mobile-number-input').removeClass('otp-validated');
        }

        $('#telephone').val(number);
        $('.sms-otp-mobile').html($("#mobile-number-input").intlTelInput("getNumber", intlTelInputUtils.numberFormat.INTERNATIONAL)); /*intlTelInputUtils.numberFormat.NATIONAL*/
    }

	/**
	 * Get Mask
	 */
	function initMask(){
		var countryData = $("#mobile-number-input").intlTelInput("getSelectedCountryData");
		if(!countryData.iso2) return false;
		var numberType = intlTelInputUtils.numberType['MOBILE'];
		var mask = intlTelInputUtils.getExampleNumber(countryData.iso2, true, numberType);
		$("#mobile-number-input").mask(mask.replace(/([0-9])/g, '0'));
	}

	initMobileInput();

	var rules = {
	   'validate-sms-phone-number': [
          function (value, element) {
              return $(element).intlTelInput("isValidNumber");
          },
          '<?php echo __("The mobile number is not valid.")?>'
        ]
    };

    $.each(rules, function (i, rule) {
        rule.unshift(i);
        $.validator.addMethod.apply($.validator, rule);
    });

});
</script>
